env:
language: node_js

node_js:
  - "node"

before_script:
  - npm run deploy
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - "node_modules"

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: wienerpizza.men
  skip_cleanup: true
  local_dir: dist
  cache_control: "max-age=21600"
addons:
  chrome: stable
